#ifndef GOBO_CORE_POSIX_CONFIG_H_
#define GOBO_CORE_POSIX_CONFIG_H_

#define GOBO_CONFIG_PLATFORM_INFO "POSIX"

#ifndef GOBO_CONFIG_LOG_OUTPUT
#define GOBO_CONFIG_LOG_OUTPUT GOBO_CONFIG_LOG_OUTPUT_PLATFORM_DEFINED
#endif

#define GOBO_CONFIG_ENABLE_PLATFORM_USEC_TIMER 1

#endif // GOBO_CORE_POSIX_CONFIG_H_
